### ISSUE TITLE
Podman go bindings in C

### ISSUE THREAD

**Issue by jmguzik** [containers/Demos#45]
There was some time ago an issue:
https://github.com/containers/podman/issues/9325
While this is almost impossible to do without significant effort, there is a way to use Go bindings in C. I created a project based on your example, and I would like to propose to add it here (I will create a PR) for future reference, as an example:
https://github.com/jmguzik/podman-bindings-c

It uses podman_go_bindings as a base to create wrapper lib, then used in C.
Let me know what you think.

**Comment by jmguzik** [comment]
@TomSweeneyRedHat Informing you as you were involved in original discussion.

**Comment by TomSweeneyRedHat** [comment]
Sounds awesome to me!

**Comment by matejvasek** [comment]
Does this works as rest api client?

**Comment by jmguzik** [comment]
Solution uses unix socket connection. According to the blog post: https://podman.io/blogs/2020/08/10/podman-go-bindings.html

**Comment by jmguzik** [comment]
I think we had a good discussion here (too good for a closed issue!): https://github.com/containers/podman/issues/9325
In the end the example I will propose is maybe not the best way for all languages which can use shared c libs, but for C/C++ I think it is a fine way to go.
I will open a PR to merge my example with Demos. I would welcome further comments.
